server:
  port : 5001

spring:
  application:
    name: TASK-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_service
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
